[package]
name = "job_control"
version = "0.1.0"
authors = ["Mike Alfaro <alfarom256@gmail.com>"]

[dependencies]
getopts = "0.2"
winapi = {version = "0.3.8", features = ["winnt", "processthreadsapi", "jobapi", "jobapi2", "minwindef", "winbase", "handleapi"]}
nt_version = "0.1"